### ISSUE TITLE
请求分享CarDD数据集

### ISSUE THREAD

**Issue by wangyouxiuya** [CarDD-USTC/CarDD-USTC.github.io#1]
您好，我对您在网上发的CarDD数据集非常感兴趣，并且对其中的内容与研究方向非常契合。给您的邮箱发了消息，不过一直没有得到您的回信。如果您能够同意共享该数据集，我将非常感激。谢谢！

**Comment by CarDD-USTC** [comment]
请访问https://cardd-ustc.github.io/，在填写许可信息后访问数据集下载链接。

**Comment by CarDD-USTC** [comment]
请访问https://cardd-ustc.github.io，在填写许可信息后访问数据集下载链接。

**Comment by CarDD-USTC** [comment]
请访问cardd-ustc.github.io，在填写许可信息后下载使用CarDD数据集。
