### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by wangyouxiuya** [CarDD-USTC/CarDD-USTC.github.io#3]
作者，您好。就是我在复现你的代码途中遇到了不少困难，对于处理MMCV相关的代码不是很熟悉。冒昧问一下，您在干这个方向之前有找到其他关于汽车损坏的数据集，并在其数据集上进行语义分割的代码吗？因为关于这方面的数据集貌似很多都没有公开，如果有的话，可以介绍分享学习一下吗

**Comment by wangyouxiuya** [comment]
我的邮箱是925688347@qq.com。您也可以直接评论，我可以到github上查看，希望可以分享经验，万分感谢！

**Comment by CarDD-USTC** [comment]
你好，其他车损数据集可参考：https://docs.google.com/forms/d/e/1FAIpQLSfuMMGafmiZ35alIgYkZeyGkR6gHhBURjxJPSe6aB6CWjN1EA/viewform
其他车损检测代码可参考：
https://github.com/neokt/car-damage-detective
https://github.com/shubhi/car-damage-assessment
https://github.com/nicolasmetallo/car-damage-detector
如果在运行本仓库代码时有疑问，请开启一个新的issue并具体描述问题。

**Comment by wangyouxiuya** [comment]
&nbsp; &nbsp; 亲爱的作者，您好。感谢你的回信，我现在的话，按照导师的意思做关于车辆检测方向的论文，但是缺少可用的baseline作为改进基础。您的CarDD: A New Dataset for Vision-based Car Damage Detection 是关于MMCV的代码，对于我来说复现以及改进确实有难度。
&nbsp; &nbsp; 你给我的：
&nbsp; &nbsp; 其他车损数据集可参考：https://docs.google.com/forms/d/e/1FAIpQLSfuMMGafmiZ35alIgYkZeyGkR6gHhBURjxJPSe6aB6CWjN1EA/viewform
其他车损检测代码可参考：
https://github.com/neokt/car-damage-detective
https://github.com/shubhi/car-damage-assessment
https://github.com/nicolasmetallo/car-damage-detector

这些似乎并没有好的论文作支撑，也没有可用的对比数据来支撑自己将来的论文。在paperswithcode我搜索了关于车辆定损的附带原码的论文，只找到了您的那一篇可用，可是对于现阶段的我确实难度偏大。我在paperswithcode上面我搜索了我能想到的所有关键词，比如;"car damage", "vehicle damage", "car detect"等，但是似乎没有什么搜索到可用的论文。因为导师是放养的管理模式，目前比较焦虑以及没有好的思路。希望作者可以帮忙指点迷境，是不是我在papaerswithcode搜索的关键词不对？希望作者可以给我提点建议，希望得到您的回信，万分感谢！！

**Comment by CarDD-USTC** [comment]
目前车损检测相关研究数量确实较少，相关代码也较少，给您提供的其他研究者的数据集和仓库已是经过充分搜索的结果。
本仓库代码所基于的MMDetection是入门门槛较低的框架，建议不必畏难，结合MMDetection的官方文档（https://mmdetection.readthedocs.io/zh-cn/latest/）投入时间研究，先将本代码跑通，然后做车损检测方法的改进或实际应用。

**Comment by CarDD-USTC** [comment]
目前车损检测相关研究数量确实较少，相关代码也较少，给您提供的其他研究者的数据集和仓库已是经过充分搜索的结果。
本仓库代码所基于的MMDetection是入门门槛较低的框架，建议不必畏难，结合MMDetection的官方文档（mmdetection.readthedocs.io/zh-cn/latest/）投入时间研究，先将本代码跑通，然后做车损检测方法的改进或实际应用。

**Comment by wangyouxiuya** [comment]
&nbsp; &nbsp; &nbsp;万分感谢你在百忙中的回信，那我就先尝试复现您的代码。
&nbsp; &nbsp; &nbsp;冒昧问一下您是老师还是学生啊，复现的过程中如果有什么不理解的地方方便请教吗？如果不方便留下联系方式也没有关系，哈哈。
&nbsp; &nbsp; &nbsp;在日后的工作中可能遇到困难，可能还会向以邮件的形式向您虚心请教。
&nbsp; &nbsp; &nbsp;最后再次感谢您的答复和帮助！！！
